---
title: "Other readings"
author: "Jacob Oram"
date: "`r Sys.Date()`"
output: html_document
bibliography: BDA.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This chapter covers other readings, including papers that have applied decision analysis in ecology and conservation biology and the ninth chapter of *Bayesian Data Analysis* [@gelman13]. 

## [@wade00] Bayesian Methods in Conservation Biology 

The main thrust of this article is that practitioners in conservation biology may find Bayesian methods far more appropriate for biological data, easier to handle and interpret when presenting results, with prior information explicitly incorporated to improve scientific transparency. 
The author first provides a simple regression example to demonstrate a situation in which Bayesian methods yield far more reasonable results (in the sense that it "matches what most people would conclude without using statistics"). 
The regression example is then included in a formal decision analysis, developing the loss functions directly (as opposed to defining a utility function and then defining $L = -U(\theta, a)$, which is the approach that Berger advocates for). 
Although this is a very simple example, it provides an excellent high-level overview of Bayesian analysis and decision theory, with a clear argument that these methods will ultimately be easier to understand and communicate when conducting conservation-oriented studies in biology and ecology. 

## [@williams16] Combining statistical inference and decisions in ecology 

The authors introduce statistical decision theory (SDT) for ecologists, noting that it has been widely applied in operations research as well as in statistics and mathematics. [In statistics, a decision rule could be a choice of estimator, such as the posterior mean; @berger85]. 
Noting that statistics originated as a sub-branch of decision theory, and that the reemergence of the Bayesian paradigm is partly due to its natural compatability with decision theory, the authors summarize the highlights of statistical decision theory that are revelant for the field of ecology -- essentially, this is briefly restating the first four chapters of @berger85. 
Following this overview, the @williams16 address two classes of problems: choosing an estimator to be reported ("optimal point estimation") and choosing a management strategy for a natural resource ("optimal resource management"). 
For the problem of optimal point estimation, the authors note that the correctly specifying the loss function is critical for appropriate inference. 

The authors illustrate optimal resource management through an example wherein land managers must decide the burn interval to optimize cumulative abundance of Henslow's Sparrows at Big Oaks National Wildlife Refuge in southeastern Indiana.  
This example provides a beautiful example of constructing a loss function from first principles (e.g., the statement that more frequent burn intervals are more costly and should have higher loss). 
The model used in the case study is 

\[
y_{j,t} \sim Poisson(A_j\lambda_{j,t}) \\
log(\lambda_{j,t}) = x_{j,t}\boldsymbol{\beta} + \eta_j \\
\]

where $y_{j,t}$ is the count of sparrows at site $j$ during time $t$, $A_j$ is the area of site $j = 1, 2, \dots, 8$, $\lambda_{j,t}$ is the unknown density of Henslows sparrows at site $j$ during time $t$, and is a function of regression coefficients $\boldsymbol{\theta} = (\boldsymbol{\beta \eta})^T$. The covariate $x$ represents the number of summers since the last burn. The random effect $\eta_j$ is a random effect that adjusts the density of Henslows sparrows at each site. The priors for this model were 

\[
\boldsymbol{\beta} \sim Normal(\boldsymbol{\mu}, \sigma^2I) \\
\eta_j \sim Normal(0,1)
\]

with $\mu^T = (-5, 2.5,0.2, 0.2)$ and $\sigma^2 = 10$ being informed by a prior study.
The abundance over which posterior uncertainty is estimated is a derived quantity resulting from $\boldsymbol{\theta}$. 

The authors' case study utilized a standard loss function (linear loss), which is in keeping with their advice to practitioners. 
They acknowledge that choosing a loss function is just as subjective as choosing a likelihood and a prior, but the body of literature is many times larger for the latter two. 
In cases where information about potential loss is lacking, the authors suggest that standard loss functions are a good starting point. 
They argue that the most important aspects to consider when constructing a loss function are the shape (e.g., convex or concave) and the symmetry. 

## [@dorazio03] Bayesian inference and decision theory: A framework for decision making in natural resource management

The authors describe the link between Bayesian methods, decision analysis and natural resource management. 
The introduction, which does not include the in-depth description of Bayesian decision theoretical machinery [as in @williams16], makes the argument essentially for the adaptation of Bayesian methods (in general; this article is old). 
However, the main thrust of the article appears very similar to @williams16. 

Notes: 
* This article touches on adaptive monitoring and makes an appeal (in the intro) to the sequential updating of state of knowledge possible in the bayesian paradigm as a reason for applying BDA in ecology. 

<hr> 

## References 

